name: "Tests"

on: [push, pull_request]

jobs:
  phpunit:
    name: "PHPUnit tests"
    runs-on: "ubuntu-20.04"

    strategy:
      fail-fast: true
      matrix:
        php: ["7.1", "8.0"]
        include:
          - php: "7.1"
            composer-args: "--prefer-lowest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          coverage: "none"

      - name: "Cache composer dependencies"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "${{ matrix.php }}-composer-"

      - name: "Cache phpunit dependencies"
        uses: "actions/cache@v2"
        with:
          path: "./vendor/bin/.phpunit"
          key: "${{ matrix.php }}-phpunit-${{ hashFiles('**/composer.lock') }}"
          restore-keys: "${{ matrix.php }}-phpunit-"

      - name: "Install dependencies"
        run: |
          echo "::group::composer update"
          composer update --no-interaction --no-progress ${{ matrix.composer-args }}
          echo "::endgroup::"
          echo "::group::install phpunit"
          ./vendor/bin/simple-phpunit install
          echo "::endgroup::"

      - name: "Run PHPUnit"
        run: "./vendor/bin/simple-phpunit -v"
